// Code generated by mockery v2.15.0. DO NOT EDIT.

package adminservice

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAtomicOperation is an autogenerated mock type for the AtomicOperation type
type MockAtomicOperation struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MockAtomicOperation) Execute(_a0 context.Context, _a1 Repository) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Repository) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockAtomicOperation interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAtomicOperation creates a new instance of MockAtomicOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAtomicOperation(t mockConstructorTestingTNewMockAtomicOperation) *MockAtomicOperation {
	mock := &MockAtomicOperation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
