// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/naofel1/api-golang-template/internal/ent/predicate"
	"github.com/naofel1/api-golang-template/internal/ent/student"
	"github.com/naofel1/api-golang-template/internal/primitive"
)

// StudentUpdate is the builder for updating Student entities.
type StudentUpdate struct {
	config
	hooks    []Hook
	mutation *StudentMutation
}

// Where appends a list predicates to the StudentUpdate builder.
func (su *StudentUpdate) Where(ps ...predicate.Student) *StudentUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *StudentUpdate) SetUpdatedAt(t time.Time) *StudentUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetFirstName sets the "first_name" field.
func (su *StudentUpdate) SetFirstName(s string) *StudentUpdate {
	su.mutation.SetFirstName(s)
	return su
}

// SetLastName sets the "last_name" field.
func (su *StudentUpdate) SetLastName(s string) *StudentUpdate {
	su.mutation.SetLastName(s)
	return su
}

// SetPseudo sets the "pseudo" field.
func (su *StudentUpdate) SetPseudo(s string) *StudentUpdate {
	su.mutation.SetPseudo(s)
	return su
}

// SetGender sets the "gender" field.
func (su *StudentUpdate) SetGender(pr primitive.Gender) *StudentUpdate {
	su.mutation.SetGender(pr)
	return su
}

// SetBirthday sets the "birthday" field.
func (su *StudentUpdate) SetBirthday(t time.Time) *StudentUpdate {
	su.mutation.SetBirthday(t)
	return su
}

// SetNillableBirthday sets the "birthday" field if the given value is not nil.
func (su *StudentUpdate) SetNillableBirthday(t *time.Time) *StudentUpdate {
	if t != nil {
		su.SetBirthday(*t)
	}
	return su
}

// ClearBirthday clears the value of the "birthday" field.
func (su *StudentUpdate) ClearBirthday() *StudentUpdate {
	su.mutation.ClearBirthday()
	return su
}

// SetPasswordHash sets the "password_hash" field.
func (su *StudentUpdate) SetPasswordHash(b []byte) *StudentUpdate {
	su.mutation.SetPasswordHash(b)
	return su
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (su *StudentUpdate) ClearPasswordHash() *StudentUpdate {
	su.mutation.ClearPasswordHash()
	return su
}

// Mutation returns the StudentMutation object of the builder.
func (su *StudentUpdate) Mutation() *StudentMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StudentUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks[int, StudentMutation](ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StudentUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StudentUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StudentUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *StudentUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := student.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *StudentUpdate) check() error {
	if v, ok := su.mutation.Pseudo(); ok {
		if err := student.PseudoValidator(v); err != nil {
			return &ValidationError{Name: "pseudo", err: fmt.Errorf(`ent: validator failed for field "Student.pseudo": %w`, err)}
		}
	}
	if v, ok := su.mutation.Gender(); ok {
		if err := student.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Student.gender": %w`, err)}
		}
	}
	return nil
}

func (su *StudentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(student.Table, student.Columns, sqlgraph.NewFieldSpec(student.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(student.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.FirstName(); ok {
		_spec.SetField(student.FieldFirstName, field.TypeString, value)
	}
	if value, ok := su.mutation.LastName(); ok {
		_spec.SetField(student.FieldLastName, field.TypeString, value)
	}
	if value, ok := su.mutation.Pseudo(); ok {
		_spec.SetField(student.FieldPseudo, field.TypeString, value)
	}
	if value, ok := su.mutation.Gender(); ok {
		_spec.SetField(student.FieldGender, field.TypeEnum, value)
	}
	if value, ok := su.mutation.Birthday(); ok {
		_spec.SetField(student.FieldBirthday, field.TypeTime, value)
	}
	if su.mutation.BirthdayCleared() {
		_spec.ClearField(student.FieldBirthday, field.TypeTime)
	}
	if value, ok := su.mutation.PasswordHash(); ok {
		_spec.SetField(student.FieldPasswordHash, field.TypeBytes, value)
	}
	if su.mutation.PasswordHashCleared() {
		_spec.ClearField(student.FieldPasswordHash, field.TypeBytes)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{student.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StudentUpdateOne is the builder for updating a single Student entity.
type StudentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StudentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *StudentUpdateOne) SetUpdatedAt(t time.Time) *StudentUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetFirstName sets the "first_name" field.
func (suo *StudentUpdateOne) SetFirstName(s string) *StudentUpdateOne {
	suo.mutation.SetFirstName(s)
	return suo
}

// SetLastName sets the "last_name" field.
func (suo *StudentUpdateOne) SetLastName(s string) *StudentUpdateOne {
	suo.mutation.SetLastName(s)
	return suo
}

// SetPseudo sets the "pseudo" field.
func (suo *StudentUpdateOne) SetPseudo(s string) *StudentUpdateOne {
	suo.mutation.SetPseudo(s)
	return suo
}

// SetGender sets the "gender" field.
func (suo *StudentUpdateOne) SetGender(pr primitive.Gender) *StudentUpdateOne {
	suo.mutation.SetGender(pr)
	return suo
}

// SetBirthday sets the "birthday" field.
func (suo *StudentUpdateOne) SetBirthday(t time.Time) *StudentUpdateOne {
	suo.mutation.SetBirthday(t)
	return suo
}

// SetNillableBirthday sets the "birthday" field if the given value is not nil.
func (suo *StudentUpdateOne) SetNillableBirthday(t *time.Time) *StudentUpdateOne {
	if t != nil {
		suo.SetBirthday(*t)
	}
	return suo
}

// ClearBirthday clears the value of the "birthday" field.
func (suo *StudentUpdateOne) ClearBirthday() *StudentUpdateOne {
	suo.mutation.ClearBirthday()
	return suo
}

// SetPasswordHash sets the "password_hash" field.
func (suo *StudentUpdateOne) SetPasswordHash(b []byte) *StudentUpdateOne {
	suo.mutation.SetPasswordHash(b)
	return suo
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (suo *StudentUpdateOne) ClearPasswordHash() *StudentUpdateOne {
	suo.mutation.ClearPasswordHash()
	return suo
}

// Mutation returns the StudentMutation object of the builder.
func (suo *StudentUpdateOne) Mutation() *StudentMutation {
	return suo.mutation
}

// Where appends a list predicates to the StudentUpdate builder.
func (suo *StudentUpdateOne) Where(ps ...predicate.Student) *StudentUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StudentUpdateOne) Select(field string, fields ...string) *StudentUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Student entity.
func (suo *StudentUpdateOne) Save(ctx context.Context) (*Student, error) {
	suo.defaults()
	return withHooks[*Student, StudentMutation](ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StudentUpdateOne) SaveX(ctx context.Context) *Student {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StudentUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StudentUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *StudentUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := student.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *StudentUpdateOne) check() error {
	if v, ok := suo.mutation.Pseudo(); ok {
		if err := student.PseudoValidator(v); err != nil {
			return &ValidationError{Name: "pseudo", err: fmt.Errorf(`ent: validator failed for field "Student.pseudo": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Gender(); ok {
		if err := student.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Student.gender": %w`, err)}
		}
	}
	return nil
}

func (suo *StudentUpdateOne) sqlSave(ctx context.Context) (_node *Student, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(student.Table, student.Columns, sqlgraph.NewFieldSpec(student.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Student.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, student.FieldID)
		for _, f := range fields {
			if !student.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != student.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(student.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.FirstName(); ok {
		_spec.SetField(student.FieldFirstName, field.TypeString, value)
	}
	if value, ok := suo.mutation.LastName(); ok {
		_spec.SetField(student.FieldLastName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Pseudo(); ok {
		_spec.SetField(student.FieldPseudo, field.TypeString, value)
	}
	if value, ok := suo.mutation.Gender(); ok {
		_spec.SetField(student.FieldGender, field.TypeEnum, value)
	}
	if value, ok := suo.mutation.Birthday(); ok {
		_spec.SetField(student.FieldBirthday, field.TypeTime, value)
	}
	if suo.mutation.BirthdayCleared() {
		_spec.ClearField(student.FieldBirthday, field.TypeTime)
	}
	if value, ok := suo.mutation.PasswordHash(); ok {
		_spec.SetField(student.FieldPasswordHash, field.TypeBytes, value)
	}
	if suo.mutation.PasswordHashCleared() {
		_spec.ClearField(student.FieldPasswordHash, field.TypeBytes)
	}
	_node = &Student{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{student.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
