// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)
