// Code generated by mockery v2.15.0. DO NOT EDIT.

package bucketservice

import (
	context "context"
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// UploadFile provides a mock function with given fields: ctx, bucketName, objName, imageFile
func (_m *MockRepository) UploadFile(ctx context.Context, bucketName string, objName string, imageFile multipart.File) (string, error) {
	ret := _m.Called(ctx, bucketName, objName, imageFile)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, multipart.File) string); ok {
		r0 = rf(ctx, bucketName, objName, imageFile)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, multipart.File) error); ok {
		r1 = rf(ctx, bucketName, objName, imageFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRepository(t mockConstructorTestingTNewMockRepository) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
