FROM golang:1.19 as build

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s

CMD ["air", "--build.cmd", "go build -o bin/monolith cmd/monolith/main.go", "--build.bin", "./bin/monolith"]
