// Code generated by mockery v2.15.0. DO NOT EDIT.

package studentservice

import (
	context "context"

	ent "github.com/naofel1/api-golang-template/internal/ent"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// CheckStudentPseudo provides a mock function with given fields: ctx, u
func (_m *MockRepository) CheckStudentPseudo(ctx context.Context, u *ent.Student) (bool, error) {
	ret := _m.Called(ctx, u)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Student) bool); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *ent.Student) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateStudent provides a mock function with given fields: ctx, u
func (_m *MockRepository) CreateStudent(ctx context.Context, u *ent.Student) error {
	ret := _m.Called(ctx, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Student) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteStudent provides a mock function with given fields: ctx, u
func (_m *MockRepository) DeleteStudent(ctx context.Context, u *ent.Student) error {
	ret := _m.Called(ctx, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Student) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindStudentByID provides a mock function with given fields: ctx, uid
func (_m *MockRepository) FindStudentByID(ctx context.Context, uid uuid.UUID) (*ent.Student, error) {
	ret := _m.Called(ctx, uid)

	var r0 *ent.Student
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *ent.Student); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Student)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindStudentByLogin provides a mock function with given fields: ctx, login
func (_m *MockRepository) FindStudentByLogin(ctx context.Context, login string) (*ent.Student, error) {
	ret := _m.Called(ctx, login)

	var r0 *ent.Student
	if rf, ok := ret.Get(0).(func(context.Context, string) *ent.Student); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Student)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindStudentsByLoginOrFirstNameOrLastNameAtOffset provides a mock function with given fields: ctx, stud, off, limit
func (_m *MockRepository) FindStudentsByLoginOrFirstNameOrLastNameAtOffset(ctx context.Context, stud *ent.Student, off int, limit int) (ent.Students, error) {
	ret := _m.Called(ctx, stud, off, limit)

	var r0 ent.Students
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Student, int, int) ent.Students); ok {
		r0 = rf(ctx, stud, off, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ent.Students)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *ent.Student, int, int) error); ok {
		r1 = rf(ctx, stud, off, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllStudentsAtOffset provides a mock function with given fields: ctx, u, off, limit
func (_m *MockRepository) GetAllStudentsAtOffset(ctx context.Context, u *ent.Students, off int, limit int) error {
	ret := _m.Called(ctx, u, off, limit)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Students, int, int) error); ok {
		r0 = rf(ctx, u, off, limit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTotalStudentByPseudoOrFirstNameOrLastNameCount provides a mock function with given fields: ctx, n
func (_m *MockRepository) GetTotalStudentByPseudoOrFirstNameOrLastNameCount(ctx context.Context, n *ent.Student) (int, error) {
	ret := _m.Called(ctx, n)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Student) int); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *ent.Student) error); ok {
		r1 = rf(ctx, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalStudentCount provides a mock function with given fields: ctx
func (_m *MockRepository) GetTotalStudentCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePseudoUsernameAndPassword provides a mock function with given fields: ctx, u
func (_m *MockRepository) UpdatePseudoUsernameAndPassword(ctx context.Context, u *ent.Student) error {
	ret := _m.Called(ctx, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Student) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStudent provides a mock function with given fields: ctx, u
func (_m *MockRepository) UpdateStudent(ctx context.Context, u *ent.Student) error {
	ret := _m.Called(ctx, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Student) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRepository(t mockConstructorTestingTNewMockRepository) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
